sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        QFzqWTFaa5A5a9R9716f7eHNqM0xi/yJsR7OFwZrEjICMyiOCACkVb08jhdOt6cfYb75FNx0e3YQEFABfMDyQZEqhBJyX5xB5p71rFvBi4qo+Y0fYLyUDLsLBBJyO02xu/VCPrI6XV4iV0kNpU8rc/crzYF2bL6tA9LQl53SZkD4a4xwO6pYsvYMJzk6b8zQXYfxwO/0tFyID1kv/aP9pWfJoSqHJXrOFqVnhOWYd0j3hQDBjO1Xm4TMcMygxRT7sU1wGWPNllhVEwb7knQbik94ekq5Hw0KQqAk6mdU8FxoYL13h6zVijffUS8qzqr8zg43fwDEMIk+lA4ZFRYH7sAfdH7vikXwbDWK3yJEvFRMzlpvaEDemX66gL8t3m7W35G6IezbvdWgMkVZT1nd+uOpKTpi+WP9Kui1j+bStVqiscT+aU6DWmAUp/BOSA/yGrAZpmQKjP5JptoBcqaR+1b1/aj3NjuOm1JPAzb/VQ9WYWSan4PKSYp+a+PZgGN5p5/nyOuz3ZokW8/OuGYwoAq/bB/HZKYD1BsmOi5K6sDMfVXiztW9+gc9u5443eCM9bBfVTzfm4GvWT177hwCDn6Qv7qN9gOOskr70pq67nxnnTFWvIFgzXz5ce06GSa6cgnurw2ub9KThUEFS63Nj+eavU7MM2pF/lsb2e+TigQ=
    - secure: >-
        RN4jGeB5vTrE/p1psUBmAjZAsYjNCdPSkxP9RoQhvUNAertzwiYMTX9pp7YLuQQJSU22Q8M5+wkX41KRi79jbMHnJQOt0+Hg5kG8o2isAOvqiHzN1sL+vPIog8XO7WPiN40BgJf39CFl9yiq/ugC0/m6Lb8l8CxXJYuAp0jRLTE2uERpN3vowLnOQH3UqgkjW2IrhwEPrdJSHPetneM5vsN991PeoAwfaldHeGdhjS6JfOCttN6VuLLtVp5d/nxLhzDck84gQd7WgqcGotaCo7bZ85vCEdeiwdAEvVWTxbR9EBnoqIggDAzEBtBQAHoB4suSwSGhkKWQyC+AyjwAT5vfda5TRPjdoXjU9/Bb2u+hmdcMhN+BNSARC8PE/dXjIfqKB0wHKU+63JYbXHs4xLPVSqMBJGIGlr3kgvLrWG1nhIu5PvMLfNc9LCZGmLjn9gM9fZGxvLK+gjQLC2TMjmGqckeLLlodR5fc37YWcqdGbO/dh751uXSI/gpd81EZgGe+RepXjofvmiwLM6fVGH2L8p5X+iiDwrc6LB3mrlim5n+bYduQiPgzXqbDcgPcZBmDK4DGi9EgIECbsN90316iihaUjslwBOdEFbOOt/R+obaHhQr2GMpjEcwtmbG/YRuyqCvEo/h3viex3y/kaSj24+j0RAWvxJmJi9yeMYU=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
