sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        nD0rEfOBOnHdZAXpRR6DMfSs0j8A32jYL5J/RThiJaEZZ2Owp7G7+bQEDB9f2S6AOKO3fp7gLDSwREp0kEhgs3c+wep4Vd9kAopkj4bCDfaDjegqrzuUA0HeFZ/rSItIddl8P/b2VwwaEi1UsXiOqNB58ZINFAeCJHBElyeIALj7KfC/IXo0v9hR4nsA6L0bh5Lmhs5HlyzOhGk/llfQnvyKv2mQfF9vi9BhLQNbZ8Mg1cW1AkI4YyglghGbU179WiHD+DCbOOL1jTtIHHM7Qf7fNxJLokWSPw0Bmzgy1k//CxdDsXYMkJTn63JfdRVtXX8xUHARrilWknTMFNmerthtjAxWRDJfRLrns+5v5jy28h6rI3DtSSCLEmhzBTzbe8gbu1VnOdnxRDPjRB3lQurBNFaTjCQt3i+FIqwA1XrxFhrw4MjJ1gzTwlA9gmTCXcvZmbtOQscVMEuEQ1owE7FaT4+FH5fQ7ptrcVh3GLISOQM2YOPOy+NxIgA374UUCGl7xDGg6STKoMphTzpiEwZzhbOYMOOA82h2te4zbPkwrtdUQtdtzjiYWIAzVOQ/V4eygxbamj7tbLRwQQ+oeZzyKz6x89tw2VgSSyLy4M2uhyjab6l9v3kqoBCzGemSLn40t5Y9zIeEaMf6WZmFF1pikgd4FguLLX+obKrQFnk=
    - secure: >-
        JgD0I2Q4RY4EO3v2qzCZGPlr+de7PIX0nxjX3lwAyIYyeNebApL2twiwMsdZey6k3AjUn+NLIt8x6U1PZyNhUxitZYdrI0YaOnVRSreZ4z7KaQHRfig0Ir3ulAH6xQC10ZMCV8JqdQAL0lact6PUodqFhEi1RDaUSRGhPkPm2vIkdH1tSjvpYYMi7zdGUCmyYsGtWWmdzht+ONq0tGkEe1ofeINS7Ok7Lt6/MzWf8v8EkYTTqpoMuIwsrwzrq2hzawJK1L9G2w2VNDb5ubV/KkTkvbJzVTIWCXzDu16mWLEhtGmGNuaEPMUIJP6UJYeMdP7dngPQealzIOGZCrvJxhlsndUwEGiZKb3HVThuJ6yD09sU38fgAg1G9GYFy2pdn7fAbqM3CBuTLEBNUy2Yq357nzQ7DGHSs46iPKRe1NquGy2fG77o8hY1YOcxjOPrafuj1GLQA0pMXdwVQ1a5mmveD4+jZp7kpmS2V3532KJIV+QIAEvxW4/wHabzpIZGbQz7qcTpz6cStwv7NhwvOuO2ahsbLOj9zRVK68nKIZBrt0e2zV/BVKEOTMbyFcUFDvVsCLgFPBztKFAKFYhbIOXNKo0mW92xHVxFRINbGOpnK0yUKi0BPdFKiNIOQL7yYEp0jSm0kjlIicjyyVbyzKfJ/CczGpezv58BD8tX0cY=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
