sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        rYjKKeNKy9bFJGUPEF+Bh9Pn9BuO7i77wlSATgszKz1d5HCwtEHeF26rSE6Axn5TSiHl01iwr6RAl1ywFK+1zvU3NHxODlTUBZ7aqQVaYrrRRqEKrMmMhcVCtvvqGXsD8a7/e62wzxDpCbWg0CvUygkLnh864bGoYH+90U+/qWi2YXKoe8g8YzrbWb5VTIqEOxQw+NaD4AWk0PW07ohYfEvQbVQ9mrsdbVXOQHMEMxcRtXIx/JwV5q73kVEY98Zno6ndDQkg1K6/4w7/Kpvjt0WQbeSAE/+65jSz8LId42SxiHWpnuT6CwMHkXh1bR3Brrvfq2YySntmsqn1KsadisFSr9GlG9zD7yy1ftoRrwpSRxrSuZJEoHaUuiTaodBTMOY8otCuDBAto4VEHRrS8rPSbbx8DbYfdH47P+/FA25L3YtkT/ubjV2LDk3Vc1q23I5pU3KIM6XoSwS9MtwKxfR+vBMuvnh6AnAU12y95L4bq9Qm1FYmL3JLRZuWxvl/C14dQlCmNqHYLOjkpQ1YRWu7mLiYUMdUOKHF0+6ZnZquiB+2Jb05aSLNfrPwrd1iCUl6Vup5jLACQzBmzg1ywYmV+85TWkv6a7Evr+RzrKacVNUrXcwAtzqTU0tyTSRJqmxAE36wy87afm4wj2VyL6Nn4LaulG6E9ZX8W8ZY55o=
    - secure: >-
        w4kuXsyjy/cN+6pdHIiGIFjrnj4VFYe6Udzn9EqwHXvFlO/vbT0klaQBU/eDuq+sDgj8M/Tw/rhhy+l8nxHiKA5SZtfWCHJgpd9DRGwHtoko7k7oRp8Vm3y0/d4CSV/bOy11sWzCW6fCnUdXYmOrDJtYc+SerEvwN6uJ/yg0assJ673FD9GwHRgmwdoUUrQ2CNYgy01YxOtvUSIovrZrj1Wv2Cob/BoQmAANI3LBQJUmNvTyCetLjWG9q/b6MmkdOlW5dbxfDzw+kTAMaXo4pmesnVqA19GCnaAfEU2OfY/Um4aShT4HSqtMpwcv1q9EOQsA+U3xRNtnE4A81FOYLtKex0qfWcpvsJCh5voOQtwHjEN0KRP3rZNVwwDbGeO/qD9+QOVVVZACTe6ZZPUaGY5m/VS+Cq+8iWsLeHN//DYo6rP17PFg/6wu93cuQwNNAW4VNuM2Ri7LlKOm5/talT6JjywNv+nIzF/WAH5jmAQ2qmRlObjRGjfR/+eqPEXVLTcUkFD0abp3DNq/pQAGrPmHq5akf1H8ui/3Iq8xJVLs2s+EpEcSZ0JvZsNdrZPW9VnQf9DVsMzDnTHO+wkZXBrFSAtEB7R+R1GEJp3R0n9y7fa1SxocZRyEsRXqWTHDBJGfFETAoAl088ZJkBQMbWnPo2/icjsOI68NnXuG6Lk=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
