sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        jkGRWICLAzRseWndbkCG6VRUvqJXUy6fcY34/x4UexWwmACdXBn6Bp2mySMKHBtD3a0XHKYLIUZ27aq84H5bg98ceNUBgEfAewS7Eyf55DpuySMc84w1hwmxl1LEl7cgPwUPQlyxAwqaY3sl5TyuEN8T75tRuS+JyOvK8qBBX3aOokoPem8z3GqAZWSLQUW/Q7N+rZRYkjZzfSvzyARjVOClpXGaMgEWoQexSEbWjXNOwDbz9RwXgdSxu7JmTKjl2lm6hx7SucC9+NpPbz8IDb3XHUKBgbqfqTw/1rrNgUkk0SIjbShLZtTqsAGcGMHy2c3WlQHQw2wUQQzpB37qV0uEEHlx4J6ALqWPsmtpeoaaSg+edf8xO+0GIjG5yfC/zi+9YjI+7ci84oQD7xqTtPNPhFJ/C2R2+o+YeQbpJrUsEr7weISqsGCcYhcKgSIfkH1Al7Ez+P0rn4/xIsYN+ZIy1Hm+DzBSY+Kpsx9x7DbwVyV+bk/frSsjLLJzyMUQwm+bw66ExIoTJRPI0J4htcPEiBTGOajMzWkt0vXtsJgPpWu+CtzB9FEPZR/P7JatfdyPmRmhhw0k5lDROWKrBW9UXCrevi8aqb6ZKaUZsIrmW7qbm1R/4BR06xXl6pr7LTPpMDM+QgDx0+i2/Pv4MIayEFmaPlSY7jVqmy0AdZI=
    - secure: >-
        rqz7IeVtDpuH1hMOqtPmtYpUut92l+ncns4MUT70iNl5e4EFdI6/xsRxtEI4iRkK+itfG65P9rQ8xPco3TkflIGIoJXxwisMltoOwITZ9oSSOQ9fH7EbmNIAvYEWWldNI2QmQ7P+CJrZvPF0twrJd8v2xCHNV5oB9pU33YaK0Kzst8uvY/2bDzOb6KqF6ykyLfdZEz7zLu2Srb35Cca7nucnFyYTyzVB9tAwu4h49mAPX5ogze6emQGV68p5sFK1BxAZ7J2eLAPVy4qRwCzrxJsCQlm2ZYg1hjmzvmFzsf50p1L959oBjX0ZLbMO9xX1xbHcja8tPhnpyRIL69TIqLFN88RQtUDwVUnjQkdvXmL6NFHvRyDRHf3nBjvUl/ngR9FhdDpgPQgb7zHYcvn+a6Va0Tavc+1wYCzZjl4xwW+ZlWD8Deg1y374JCA3IvtBHv8xC7lP49Noj4fS8ufuXnhhYzOXMUAZE0XG7Tr92Ujax1uIoclxLwqPEObV06SUZ3koFw4HJdJj8xrEX2E6UJMGBeDUnyw/FjJ9yoUPiWu62qzGXgqfEuVDdJ+/IrjCwB1doJwwGi96uFpZVgxiMGQOWI1rsMJsCl1ZgA1C/m0XMsoVi4fNeS+B6yKv4giv25psRywYKBS1ynTVJGqkW1O8mubTBNC21fItF9uzt/w=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
