sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        rm5RvNMhz0MvGi0tQiiQAkXweiULaX4Fc+CniMcy0WmtmOd1TLHajO2VAEUhFzevyNZByzwUORs1AYZHuIyP0K7hHbKDMFRtThxJwBZjWQ/ZrwgDM95wKtDr9g38BTSs0NrgoRW0uDl2hPwpTpWN1KFSo8vxkYzx0acZT3VvyQ9777+Ml10xNqcPblnZnu07gdcQjQxRfLRH3kAX/NT+yYxnrZTnyGaIztTDGlUGlGMMUtIu0m3KyAT90vaklsdukeew+99i8VdmfRuzdNFFUgPhGcqK69uwDZZCqNRd0XELuxgfHtn96RYlQr3YoBvHOz5dib/esbLIxNw2xmA8ZN4WK9HrURZKQby4VBzJBM2Fwa5ydR3UQxIVnWQdrRH2DYZ6wCYRt1SsNB8xALp8+DSZtqOgN4zs3kyJlJuQnhESA9Mc9h4BhX5iocSd2F+DZJTMu+rwmlEIV1LK27JhQpYtyCcvhFEmVr03Rpkiw2S6x7r94mwyMt2rOdVAHbbYvHSyZDgUK4paJRPPmk11eS6SA8u7jQRlG6CO7Hh6jWsjR3YsK+0g505hsDFpJKxMvPvNkrjRXqyBG7X62/6SHIN0uNBYzb3KZqr5cbWjSIVnU8D+UweIWAOFqhnwO/GuDrq7l2jnMSvaTsAK5kMAfsr5V44F9ZrafSSf7d9BTqk=
    - secure: >-
        imqaQiVqA/k7DpN/SwPv/Tfzm1NrR//HxaG2PmGCeXmfDzlrc8FPKklFWbW2IFM7eJ3TGT1/6tGYg1dqMkA7YP6olhSCMV1jwT88TZKmQ6aFTA51jL8YLysNfTxBlRd6jBF0y3DWmVOltoHKq1VyAKl0y+DxC0JjwyHgqBIarsNDKdkzBy+DY6pPpO4bBMvtC4UcgsR3S5WFJIL2KGvYMv7R/eB/iMYDByQnxN+bJ1YhiPsCg69AIcnxIxEyd+/k5I52zTBIkIPtaeKpGwxtlpjPuFFyLT3DW54C6HwAURm3W7AT/UD8M4TBAzxHqx5kAaAirhjRkoRnFhMRjr4R8lhX1KVgkbXZZ7qmOHRJ/8hgoQwspbbtX0sd+gBeKp2i7Z3JWejZHJ2TMF11X2pk9yVMQrEInbCx6UrbGQyltDIaMQ3GIrMY/g/CaeqcMNw7BfGIbqyqMysmGQKsgo3/bUHWDqHUZur2uhbJLnlMZk/Hc4eGKRBWrfoh4G6/ClEVVRZhumkH+6jWHmVK/GmKGjA17Hs4bO3ulDOV4cMqbMXGzInfLnu0kbyJesn5Q8/YfJoV1KRkYQly2PfzXyR0l6LPRRYDqMFIIPKKHzNwHYKQanrQ47hUuIMGl0XsH/gymrqHr/l7KZ2/Y50JhcucoSW9B3d/40xAksTPgDPFfPM=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
