sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        UeXjhjZtdARVGhv4ImvRqLRvVKcouwt5ZvjxlTKVqtXxoekxj103Lu3f+JiuPtGiXbA+OucQx1Vknf8ac/DozlJbq93ktSFqTDHSYVR20hBmxJgXj0ClIM1Gx3FREAwpW3Z20INtLz4EmuJsLoisz3TYx258ONmqIH9P6TU9LhyCqxiaXR+t8RNLi0Kr8yy9lxsD29m6TGiP+W7W7HOwH8DTdrR0shD25uSILmDLWK8M4EZ3gRMUNQowpVMK6zLSdZe3Bgs+DSPT8/sJXsR0y2ksWo+CPzpeN8YN5EmqwuDHkZuw6/Jz94mAbFZUyOfRadxmnDPBSChtURQvJVY5+Wwie6o7Nj6OxU8+H90xL7Ky1chF3Nxp8S7L8emFbj5KH8pi9ZEXK05kNL7C9yVB2KuSM1evbm6E5KRZm6LXVb5Y7A4MqU+KexzVj0+/US8svM063HePYndAfY/nT7nmTWoR3VGVPiO2m2/zRZuXS3rqOoFkhMVFA2bUfOHjd5Da9eetITrrIZ7BmLGCfmjTeK60aDeL3zvvgSarTFTr5jxLch0ET8L0dZltbuOHDmq0G7hzsHiHR93fgimBDjRAIybQwli3Ka5pYBmTWI8EfWQyDYtA9iI+3plknJc4oB+b0Yupd3vMYzTF//XxmDCwKEqFal0axPsXN+oWZDiBtoI=
    - secure: >-
        Ie/nGrdTCwV59/rt9kiLIiPQXjw/wCcNBhryB2VTWvuv9ek47ckP9NaRJvWQ64oylj97WDIWXEqKruNJGFDZOS8IOGk371vU3SS4wNpIxyg7SrhaT0GaaCqlZ5aBTx47puNMH8pSAq4iYLIa+xG59DptqV/sQQiGfN5bAnJjKcWUcvANKcKNwu3NSoTVg9Upvj3FB5uaUqI9L10/S7Ey7ikqPlb/Zby+eEGSH8NaR4xk0vMlkr4CL+szbXbBom92S8RfR0WUgXapLdAypGzPrETPtgxr9fHG2r6Fc58LtomwtIl3ddqwTvpxFZuqMUogV4T6uU8dSaAWnTjXqYaImECbsLjwshAtxyrk70tztZpRiHeTDDt1mXHU4w1zqWvypLDWJAXYrAug5R4vtvch7TsCifjnoEudwouu8N08O6BG8nI/Z1Aah+r2lUoOEiD8yIlbB1jP17feJ84SrAe1Bht8vsmx52aZ5xwvF6hX5GdbCmP6QvkOvuhWX7V9vWddHF8/ALui7gb96Xt7AOR7m71dCdf835fNSVUHfyHrcMJ9LP38jTuRA7xftjnLeJtLhRKQB2L1guJY6ecPccAqC7MOLIISaROgumcIcO9VK7HhJmmXawwVClg7uMGX2Q6t6+aUg++SyRfkZuE7a4x3qhhNIs/Mxu2i9UEnTF8dKRs=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
