sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        CRymdcHKIZWGpRdfn7ModZzXDyti4OtytMCqk6jd1hZmtEO75QbN+8NWE7m3hPQURjGzrrTqJsRfGTIv+Zsg+o/zcxUuBDRAmdUbGmZk2k/wX3DH/VLNRKEhArYjOYCRMPJSyFanbbuSh/23kt7E6bn78EWPnGK2zeb8oDVISKmJ7VEPsdHG9Iyno9d3yVH9RwIEIbVJUZv/xhqlTr4J59PLtv3M481jSSlG66G2FXC/nrHhOYtPVxv0jYhBk093U7a9yCjA2OdrXmxV6dOdkItQwLuY+psmOfiuecof4vuvLKStXteZc6YZeLADwozWjLv2pTSnO+6IXgALX4x2NMsxHIFedw/OtMAipTQRsXAB8ULUZIUcdkQzYLRIGwkz1UAgfxoTVLlVwKnCVLrb6ca9sb/z0kY9UODNjHzMkzHYq0biMYkk8lAVfYu75NGfezU09UaIcdYzmu4zJUUrRUfm4b8wMhtNDlkCSlnrvgV1AE5KBPoi3u2FSPtLkTChB96jkFn0pH6plWuR0cCVnXHvqD3cGohdLioVaAJYmYoTpCK2+xSpkN2WVz7q6ozpDrmpUfKbr3xadffRcybFlOmfbeya3llQIblH02+14IGY5yHvWGH/e4hoN+8M/XsAVctXVtAMP5+LbApY6j7pEZoesVl8X7m2UyC0Ih9NADI=
    - secure: >-
        gHW3k/qOb7QnZLF+JKhFXpeukPSaVpLUiUulgUiZhP3WYwF9SEOYHPWVMVhqg8gJZCHYaFe7V/PxrMYDVyQ/0UNaJA6inNnwtpMWK+1FLAgm82sM7APCIIS98281d7izuLfTOrEdUvSNUDx77yddpB58xzYoEejjy5QVYFa3LAw8XMr3peuKjcGOwnIkjMIJ+ICe6Z4gdG3amBaRuWe3kKTcphmnGEt4jw42EGtzcdc1Q6iOvwTxV8n0Urc4135Rs+2MTGqskTtD/PR9i3eIaNM+cP1mr0QYfnkkLzLI672243pSNScwceOe4kGDU8nzm7Symopjiqj6FGBVNkARBoX72oV7mneNZrfrtEMxwm7Js0qUopLQZYi4nYc0LfJwH/OUPgdE+GhgzdgTlayFbIOJJQPpu16WDi3V4Xf5P7qiLiTFcWiHP4nIK3VRVMSP7uLTE9nE95CD9h3qSOTcdnLMgNA10bb4/2u2tXrXNxVQq1CSBI56oAqbLjPvJKKXiUSTL0k+mu+FpNFddbUn7lhakNndJ5aoV/U1jzQJuebUKiRStU1H/kJPnCTwCABN3WUj5MjepjvekYmy/Vet33eoifiMduC5M5tpocfB8z4X5bmkuxovLi4TYP2kX58hoPDlHGRh1sZKXZaui+9FgPFYuwiyHkO5vlqInVAX6Gc=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
